# Copyright (c) 2026 tom96da
# SPDX-License-Identifier: MIT OR Apache-2.0

packages:
  - "packages/*"
  - "examples/*"
  - "npm/*"
minimumReleaseAgeExclude:
  - "@vitest/mocker@5.0.0"
  - "@vitest/spy@5.0.0"
  - vitest@5.0.0
